In [1]:
!pip install numpy

In [3]:
import numpy as np

In [14]:
arr = np.array([[1,2,3,4],
               [2,3,4,5],
               [3,4,5,6]])
print(arr[0:3,3])
print(arr[2,1:2])

[4 5 6]
[4]


In [20]:
a = np.array([[10,20,30],
               [20,30,40],
               [30,40,50]])
print(a[0:3,1])
print(a[2,1:2])

[20 30 40]
[40]


In [36]:
r = np.eye(6)
print(r[0:3,3])
print(r[2,1:2])
print(r)


[0. 0. 0.]
[0.]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [42]:
data1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(data1.size)
print("-----------------------------------")
newdata = data1.reshape(3,5)
newdata1 = data1.reshape(5,3)
print(newdata)
print("-----------------------------------")
print(newdata1)

15
-----------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-----------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [44]:
x= np.array([[1,2,3],[2,3,4]], dtype=np.float64)
y= np.array([[10,20,30],[20,30,40]], dtype=np.float64)

In [46]:
print(x+y)
print(np.add(x,y))

[[11. 22. 33.]
 [22. 33. 44.]]
[[11. 22. 33.]
 [22. 33. 44.]]


In [48]:
print(x-y)
print(np.subtract(x,y))

[[ -9. -18. -27.]
 [-18. -27. -36.]]
[[ -9. -18. -27.]
 [-18. -27. -36.]]


In [52]:
print(x*y)
print("-----------------")
print(np.multiply(x,y))

[[ 10.  40.  90.]
 [ 40.  90. 160.]]
-----------------
[[ 10.  40.  90.]
 [ 40.  90. 160.]]


In [54]:
print(x/y)
print(np.divide(x,y))

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
