In [5]:
!pip install numpy

In [6]:
import numpy as nup

In [12]:
a= nup.array([1,2,3])
b= nup.array([(1,2,3) ,(2,3,4)], dtype = float)
c= nup.array([[(2,3,4), (3,4,5)],[(3,2,1),(3,8,5)]], dtype = float)
print(a)
print(b)
print(c)

[1 2 3]
[[1. 2. 3.]
 [2. 3. 4.]]
[[[2. 3. 4.]
  [3. 4. 5.]]

 [[3. 2. 1.]
  [3. 8. 5.]]]


In [14]:
nup.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
nup.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
data = nup.arange(1,50,5)
print(data)

[ 1  6 11 16 21 26 31 36 41 46]


In [22]:
nup.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
data1 = nup.full((10),10) #1D example
print(data1)
print(data1.ndim)

[10 10 10 10 10 10 10 10 10 10]
1


In [27]:
data2 = nup.full((2,2),100) #2D example
print(data2)
print(data2.ndim)

[[100 100]
 [100 100]]
2


In [29]:
data3 = nup.full((3,3,3),50) #3D example
print(data3)
print(data3.ndim)


[[[50 50 50]
  [50 50 50]
  [50 50 50]]

 [[50 50 50]
  [50 50 50]
  [50 50 50]]

 [[50 50 50]
  [50 50 50]
  [50 50 50]]]
3


In [31]:
d1= nup.eye(6) #Identity matrix example
print(d1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [35]:
arr = nup.array([[1,2,3],
                  [2,3,4],
                  [4,5,6]])
print(arr.shape)

(3, 3)


In [39]:
arr = nup.array([[1,2,3,6],
                  [2,3,4,6],
                  [4,5,6,7],
                  [1,2,3,4]])
print(arr.shape)
print(arr.size)

(4, 4)
16


In [41]:
arr = nup.array([[1.8,2.1,3.2,6],
                  [2.1,3,4,6],
                  [4.2,5,6,7],
                  [1,2.3,3,4]])
print(arr.shape)
print(arr.size)
len(arr)

(4, 4)
16


4